package io.nodusdb.storage;

enum UpgradeStep {
    LEGACY_RECOVERED,
    BACKUP_FILE_COPIED,
    BACKUP_INSTALLED,
    TRIPWIRE_WRITTEN,
    STAGING_BUILT,
    LOG_INSTALLED,
    SNAPSHOT_INSTALLED,
    FORMAT_WRITTEN,
    LEFTOVERS_REMOVED
}
